name:                subseq-impure
version:             0.1.0.0
github:              "xmpf/subseq-impure"
license:             BSD3
author:              "Michalis Papadopoullos"
maintainer:          "el14702@mail.central.ntua.gr"
copyright:           "GPLv3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/xmpf/subseq-impure#readme>

dependencies:
- base >= 4.7 && < 5
- array
- massiv
- containers

library:
  source-dirs: src

executables:
  subseq-impure-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subseq-impure

tests:
  subseq-impure-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - subseq-impure
